"""Renamed Workbook to WorkbooksList, added new Workbook table

Revision ID: 2705d93f7484
Revises: 1a1ad275f74b
Create Date: 2025-03-27 17:48:35.587397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2705d93f7484'
down_revision = '1a1ad275f74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workbooks_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=512), nullable=False),
    sa.Column('img', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workbook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=False))
        batch_op.drop_column('img')
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workbook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('img', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
        batch_op.drop_column('data')

    op.drop_table('workbooks_list')
    # ### end Alembic commands ###
